url: https://www.webmanajemen.com/chimeraland/
permalink: :title.html #:year/:month/:day/:title.html
permalink_defaults: :title.html
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

public_dir: build
source_dir: source