language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

# track upstream node_js matrix:
# - https://github.com/hexojs/hexo/blob/master/.travis.yml
# - https://github.com/sass/node-sass/blob/master/.travis.yml
node_js:
  - "6"
  - "8"
  - "10"
  - "node"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      - gcc-4.9
      - g++-4.9

# https://github.com/sass/node-sass/blob/0c31dc2/.travis.yml#L73-L88
before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      if [[ $(node -v) =~ v1[01] ]]; then
        export CC="gcc-4.9";
        export CXX="g++-4.9";
        export LINK="gcc-4.9";
        export LINKXX="g++-4.9";
      else
        export CC="gcc-4.7";
        export CXX="g++-4.7";
        export LINK="gcc-4.7";
        export LINKXX="g++-4.7";
      fi
    fi

script:
  - npm run lint
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js